
name: CI for E2E Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      -master

jobs:
  build-and-test:
  runs-on: ubuntu-lastest
  steps:

  # 1. Configurar el repositorio
  - name: Checkout code
    uses: actions/checkout@v3


  # 2 Configuracion JDK

  -name: Set up JDK 21
  uses: actions/setup-java@v3
  with:
      distribution: "temurin"
      java-version: 21

  # 2.1 Configuracion Gradle

    -name: Gradle configuraion y cache
  uses: actions/cache@v3
  with:
      path: ~/.gradle/caches
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      restore-keys: |
      ${{ runner.os }}-gradle-

  #3 Permisos

    -name: Configuracion de permisos
    run: chmod +x ./gradlew



  # validaciones
    -name: validar gradlew
    run: ./gradlew wrapper --gradle-version 7.6.1

  # Ejecutar

    -name: Run test in CI mode
    run: ./gradlew test --tests "org.nttdata.runner.EjecutarLogin" --info

